title: "Canatto Filipe"
description: "Escrevo sobre programação, matemática e afins."
author: "canattofilipe"

theme: minima

markdown: kramdown
plugins:
  - jekyll-feed

head_custom: |
  <script>
    MathJax = {
      tex: {
        inlineMath: [['$', '$'], ['\\(', '\\)']]
      }
    };
  </script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

